---
title: "get_compile_data"
output: html_document
date: Oct-07-2024
author: Md Aminul Islam Prodhan
toc: false
---


## Function: `get_compile_data`

### Overview
`get_compile_data` is a versatile function designed to filter out toxicokinetic (TK) and recovery animals from a study database. The function takes various inputs to specify the study ID and database path, and it includes options for handling both SQLite and `.xpt` file formats, particularly when dealing with data generated by the SENDsanitizer package. The primary aim is to clean and compile study data, ensuring that the results are focused on the target set of animals.

### Function Parameters
- **`studyid`** *(Mandatory, Character)*:  
  The study ID number, which uniquely identifies the study within the database.

- **`path_db`** *(Mandatory, Character)*:  
  The path to the database file. This could be a path to an SQLite database or a directory containing `.xpt` files.

- **`fake_study`** *(Optional, Boolean)*:  
  Indicates if the study data has been generated using the SENDsanitizer package. Defaults to `FALSE`.

- **`use_xpt_file`** *(Optional, Boolean)*:  
  Specifies whether to use `.xpt` file format when dealing with data generated by the SENDsanitizer package. Defaults to `FALSE`.

### Return Value
The function returns a cleaned and compiled data frame with filtered study data, ready for further analysis.

### Key Features
1. **Data Fetching**: Establishes a connection to the database (or reads `.xpt` files) and retrieves necessary domain data such as `dm` (Demographics) and `ts` (Trial Summary).
2. **Data Processing**: Performs data transformations, including renaming columns, updating values, and selecting relevant columns.
3. **Filtering Logic**:
   - Converts "Control" groups to "vehicle" and retains only animals in the "vehicle" or "HD" (high-dose) groups.
   - Removes recovery animals using the `ds` (Disposition) domain.
   - Excludes toxicokinetic (TK) animals for rat studies by analyzing the `pp` (Pharmacokinetics) and `pooldef` domains.
4. **Species Detection and Handling**: Extracts species information from the `ts` domain to customize the filtering logic for different species.

### Example Usage
#```{r}
# Example call to get_compile_data
# Note: Replace 'path/to/database.db' with the actual path to your database
#get_compile_data(studyid = '1234123', path_db = 'path/to/database.db')





