
#' @title get LB score for a given studyid
#' @param studyid Mandatory, character \cr
#'   Studyid number
#' @param path_db Mandatory, character \cr
#'   path of database
#' @param fake_study optional, Boolean \cr
#' whether study generated by SENDsanitizer package
#' @param use_xpt_file Mandatory, character \cr
#'   Studyid number
#' @param master_compiledata Mandatory, character \cr
#'   path of database
#' @param return_individual_scores optional, Boolean \cr
#' whether study generated by SENDsanitizer package
#' @return score
#'
#' @examples
#' \dontrun{
#' get_lb_score(studyid='1234123', path_db='path/to/database.db')
#' }
#' @export

get_lb_score <- function(studyid = NULL,
                         path_db,
                         fake_study= FALSE,
                         use_xpt_file = FALSE,
                         master_compiledata = NULL,
                         return_individual_scores = FALSE) {

  studyid <- as.character(studyid)
  path <- path_db

  # Helper function to fetch data from SQLite database
  fetch_domain_data <- function(db_connection, domain_name, studyid) {
    domain_name <- toupper(domain_name)
    query_statement <- paste0('SELECT * FROM ', domain_name, " WHERE STUDYID = :x")
    query_result <- DBI::dbGetQuery(db_connection, statement = query_statement, params = list(x = studyid))
    query_result
  }

  # GET THE REQUIRED DOMAIN DATA
  if (fake_study == TRUE && use_xpt_file == FALSE){

    # Establish a connection to the SQLite database
    db_connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = path)

    # Fetch data for required domains
    lb <- fetch_domain_data(db_connection, 'lb', studyid)

    # Close the database connection
    DBI::dbDisconnect(db_connection)

  } else if (fake_study == TRUE && use_xpt_file == TRUE){

    # Read data from .xpt files
    lb <- haven::read_xpt(fs::path(path,'lb.xpt'))

  } else if (fake_study == FALSE && use_xpt_file == FALSE) {

    # Establish a connection to the SQLite database
    db_connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = path)

    # Fetch data for required domains
    lb <- fetch_domain_data(db_connection, 'lb', studyid)

    # Close the database connection
    DBI::dbDisconnect(db_connection)

  }else if (fake_study == FALSE && use_xpt_file == TRUE) {

    # Read data from .xpt files
    lb <- haven::read_xpt(fs::path(path,'lb.xpt'))

  }

    LB_selected_columns <-  lb[ , c("STUDYID", "DOMAIN", "USUBJID", "LBTESTCD",
                                  "LBTEST", "LBCAT", "LBORRES", "LBORRESU", "LBSTRESC", "LBSTRESN", "LBSTRESU", "LBSPEC", "VISITDY", "LBDY")]

    # convert the "LBSTRESN" column to numeric
    LB_selected_columns$LBSTRESN <- as.numeric(LB_selected_columns$LBSTRESN)

    # Remove rows with NA  values in the LBSTRESN column
    LB_selected_columns <- LB_selected_columns[!is.na(LB_selected_columns$LBSTRESN),]

    # Remove rows with  "o" values in the LBSTRESN column
    LB_selected_columns <- LB_selected_columns[!(LB_selected_columns$LBSTRESN) == 0,]

    #Make LB Data Data Frame to Hold Information
    LBData <- data.frame("STUDYID" = NA,"USUBJID" = NA,"LBSPEC" = NA,"LBTESTCD" = NA,
                         "LBSTRESN" = NA, "VISITDY" = NA)



    # for (Name in unique(filtered_combined_lb$STUDYID)) {
    # Filter the data for the current STUDYID
    #study_data_LB <- lb
    study_data_LB <- LB_selected_columns

    # Check if LBDY column exists and process accordingly
    if ("LBDY" %in% names(study_data_LB)) {
      LBD <- study_data_LB %>%
        dplyr::filter(LBDY >= 1) %>%
        dplyr::select(STUDYID,USUBJID, LBSPEC, LBTESTCD, LBSTRESN, LBDY)

      colnames(LBD) <- c("STUDYID", "USUBJID", "LBSPEC", "LBTESTCD", "LBSTRESN", "VISITDY")

      # Convert LBCAT to LBSPEC if LBSPEC is NA
      if (all(is.na(LBD$LBSPEC))) {
        LBD$LBSPEC <- study_data_LB$LBCAT[study_data_LB$LBDY >= 1]

        if (any(c("HEMATOLOGY", "Hematology","hematology") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("HEMATOLOGY", "Hematology","hematology"),
                                   levels(LBD$LBSPEC))] <- "WHOLE BLOOD"
        }
        if (any(c("CLINICAL CHEMISTRY","Clinical Chemistry") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("CLINICAL CHEMISTRY","Clinical Chemistry"),
                                   levels(LBD$LBSPEC))] <- "SERUM"
        }
        if (any(c("URINALYSIS","Urinalysis") %in% levels(LBD$LBSPEC))){
          levels(LBD$LBSPEC)[match(c("URINALYSIS","Urinalysis"),
                                   levels(LBD$LBSPEC))] <- "URINE"
        }
      }
    } else {
      # If LBDY column does not exist, handle accordingly
      LBD <- study_data_LB[which(study_data_LB$VISITDY >= 1),
                           c("STUDYID","USUBJID","LBSPEC","LBTESTCD","LBSTRESN", "VISITDY")]
    }

    # Add to LBData
    LBData <- rbind(LBData, LBD)

    # Remove rows with all NAs
    LBData <- stats::na.omit(LBData)

    # Concatenate LBSPEC and LBTESTCD
    #LBData$LBTESTCD <- paste(LBData$LBSPEC, LBData$LBTESTCD, sep = ' | ')

    #Remove Not Included Tests...............................................................
    # This step remove not rows matching test from ogransystem
    #test_cleaned_LBData <- LBData[LBData$LBTESTCD %in% organTESTCDlist[['LIVER']],]

    test_cleaned_LBData <-  LBData

    # Create a new data frame with the row having the max VISITDY for each USUBJID and LBTESTCD combination
    max_visitdy_df <- test_cleaned_LBData %>%
      dplyr::group_by(USUBJID, LBTESTCD) %>%
      dplyr::filter(VISITDY == max(VISITDY, na.rm = TRUE)) %>%
      dplyr::ungroup()


  # master_compiledata <- get_compile_data(studyid, path_db,fake_study = fake_study)

    #<><><><><>... Remove TK animals and Recovery animals......<><><><><><>.
    #<><> master_compiledata is free of TK animals and Recovery animals<><><>

    if (is.null(master_compiledata) && fake_study == TRUE && use_xpt_file == FALSE) {
      # Call the master_compiledata function to generate the data frame for fake study
      master_compiledata <- get_compile_data(studyid, path_db, fake_study = fake_study, use_xpt_file = use_xpt_file)

    } else if (is.null(master_compiledata) && fake_study == TRUE && use_xpt_file == TRUE) {
      # Call the master_compiledata function to generate the data frame for fake study using xpt file
      master_compiledata <- get_compile_data(studyid, path_db, fake_study = fake_study, use_xpt_file = use_xpt_file)

    } else if (is.null(master_compiledata) && fake_study == FALSE && use_xpt_file == FALSE) {

      master_compiledata <- get_compile_data(studyid, path_db, fake_study = fake_study, use_xpt_file = use_xpt_file)

    } else if (is.null(master_compiledata) && fake_study == fake_study && use_xpt_file == TRUE) {

      # Call the master_compiledata function for real study using xpt file
      master_compiledata <- get_compile_data(studyid, path_db, fake_study = fake_study, use_xpt_file = use_xpt_file)
    }


    # Filtering the tk animals and the recovery animals
    # Remove the TK animals and Recovery animals
    LB_tk_recovery_filtered <- max_visitdy_df %>%
      dplyr::filter(USUBJID %in% master_compiledata$USUBJID)

    # Perform a left join to match USUBJID and get ARMCD ## 020924
    #-inner_join() used instead of left_join()#199
    LB_tk_recovery_filtered_ARMCD <- LB_tk_recovery_filtered %>%
      dplyr::inner_join(master_compiledata %>% dplyr::select(USUBJID, ARMCD), by = "USUBJID")


    lbtestcd_list <- unique(LB_tk_recovery_filtered_ARMCD$LBTESTCD)

    # Initialize an empty data frame for the final results
    final_results <- NULL

    # "zScore Calculation" for LB data
    # First subset the LB_tk_recovery_filtered_ARMCD data frame

    # .................Filtering data for each unique "LBTESTCD" value........

    for (lbtestcd in lbtestcd_list) {
    current_lbtestcd_df <- LB_tk_recovery_filtered_ARMCD %>%
      dplyr::filter(LBTESTCD == 'lbtestcd')

    # calculate the zscore for the current LBTESTCD
    zscore_df <- current_lbtestcd_df %>%
      dplyr::group_by(STUDYID) %>%
      dplyr::mutate(
        mean_vehicle_alt = mean(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE),
        sd_vehicle_alt = stats::sd(LBSTRESN[ARMCD == "vehicle"], na.rm = TRUE)
      ) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(
        zscore = (LBSTRESN - mean_vehicle_alt) / sd_vehicle_alt)%>%
      dplyr::mutate(zscore = abs(zscore))

    # Average z-score per STUDYID for all subjects with the current LBTESTCD'
    final_zscore <- zscore_serum_alt %>%
      dplyr::filter(ARMCD == "HD") %>%  # Step 1: Filter for HD
      dplyr::group_by(STUDYID) %>%  # Step 2: Group by STUDYID
      dplyr::summarise(
        avg_zscore = mean(zscore, na.rm = TRUE),  # Step 3: Average alt_zscore
        LBTESTCD = dplyr::first(LBTESTCD)) %>% # Include LBTESTCD in the summarized data
      dplyr::select (STUDYID, zscore )%>% #select (avg_alt_zscore ) %>%
      dplyr::mutate(zscore = ifelse(zscore >= 3, 3,
                                            ifelse(zscore >= 2, 2,
                                                   ifelse(zscore >= 1, 1, 0))))


    }


    print(serum_alb_final_zscore)
    print(serum_ast_final_zscore)
    print(serum_alp_final_zscore)
    print(serum_alt_final_zscore)
    print(serum_bili_final_zscore)
    print(serum_ggt_final_zscore)


    # Merging----------LB----zscores------------values-------------------
    LB_zscore_merged_df <- serum_alb_final_zscore %>%
      dplyr::full_join(serum_ast_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_alp_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_alt_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_bili_final_zscore, by = "STUDYID") %>%
      dplyr::full_join(serum_ggt_final_zscore, by = "STUDYID")


    # Replace Inf, -Inf, and NaN with NA in the selected columns
    selected_cols <- c("avg_alb_zscore", "avg_ast_zscore", "avg_alp_zscore",
                       "avg_alt_zscore", "avg_bili_zscore", "avg_ggt_zscore")

    LB_zscore_merged_df[selected_cols] <- lapply(LB_zscore_merged_df[selected_cols],
                                             function(x) replace(x, is.infinite(x) | is.nan(x), NA))


    if (return_individual_scores) {

      # Master LB list
      master_LB_list <- data.frame(STUDYID = NA, avg_alb_zscore = NA, avg_ast_zscore = NA, avg_alp_zscore = NA,
                                   avg_alt_zscore = NA, avg_bili_zscore = NA, avg_ggt_zscore = NA)

      # Add LB_zscore_merged_df to master dataframe
      master_LB_list <- dplyr::bind_rows(master_LB_list, LB_zscore_merged_df)

      master_lb_scores <- master_LB_list #%>% master_lb_scores[-1,]
      master_lb_scores   <- master_lb_scores[-1,] # remove the first column


    } else {
      # Calculate the average for each row, ignoring NA values
      LB_zscore_merged_df$avg_all_LB_zscores <- rowMeans(LB_zscore_merged_df[selected_cols], na.rm = TRUE)

      # select the specific columns for calculation
      LB_all_liver_zscore_averaged <- LB_zscore_merged_df %>% dplyr::select (STUDYID, avg_all_LB_zscores)

      # Assigning the new variables
      LB_final_score <- LB_all_liver_zscore_averaged

      # Create "LB_df" for FOUR_Liver_Score
      averaged_LB_score <- LB_final_score %>% dplyr::rename(LB_score_avg = avg_all_LB_zscores)


    }


  if (return_individual_scores) {
  return(master_lb_scores)
 } else {
   return(averaged_LB_score)
 }

}
